# Generated by Django 2.2.17 on 2020-12-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_reputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='porteMonnaie',
            field=models.IntegerField(default=500),
        ),
    ]
