# Generated by Django 2.2.17 on 2021-01-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='dateFinancement',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='estFinance',
        ),
    ]
