# Generated by Django 2.2.17 on 2020-12-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0002_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='montantVoulu',
            field=models.IntegerField(default=0),
        ),
    ]
