# Generated by Django 2.2.17 on 2020-12-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0003_projet_montantvoulu'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='montant',
            field=models.IntegerField(default=0),
        ),
    ]
