# Generated by Django 2.2.17 on 2020-12-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0005_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='dateFinancement',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='projet',
            name='estFinance',
            field=models.BooleanField(default=False),
        ),
    ]
