# Generated by Django 2.2.17 on 2020-12-23 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0009_auto_20201223_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='dateFinancement',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
