# Generated by Django 2.2.17 on 2020-12-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0010_auto_20201223_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='dateEvaluation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
