# Generated by Django 2.2.17 on 2020-12-26 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0011_auto_20201226_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='dateEvaluation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projet',
            name='dateFinancement',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
